sudo: false
language: python
python:
- '3.4'
- '3.5'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wv
env:
- TSI2_LING7='coverage run --source=詞頻doc -m unittest'
- TSI2_LING7='flake8 . --exclude=venv --count --show-source --ignore=E501'
install:
- pip install beautifulsoup4 lxml
- pip install flake8 python-coveralls
branches:
  only:
  - master
  - /\d+\.\d+\.\d+/
script:
- echo $TSI2_LING7
- $TSI2_LING7
after_success:
- coverage report
- coveralls

