#!python
import json
from os import walk
from os.path import join


def 揣規个資料夾(來源):
    全部名 = set()
    for 所在, _資料夾, 檔名陣列 in walk(來源):
        for 檔名 in 檔名陣列:
            來源檔案 = join(所在, 檔名)
            with open(來源檔案) as 檔:
                資料 = json.load(檔)
            for k in 資料.keys():
                全部名.add(k)
            for s in 資料['資料']:
                for k in s.keys():
                    全部名.add(k)
                if len(s['段']) == 0:
                    print(來源檔案)
#                 全部名.add(str(len(s['段'].split())))
    print(sorted(全部名))

if __name__ == '__main__':
    #     資料=揣規个資料夾('JSON格式資料')
    資料 = 揣規个資料夾('/home/Ihc/git/Ungian_2011_KIPsupin/JSON格式資料')
    資料 = 揣規个資料夾('/home/Ihc/git/kok4hau7-kho3pun2/JSON格式資料')
    資料 = 揣規个資料夾(
        '/home/Ihc/git/Pakhelke-1916_KoTan-1975_hiantaiekpun-2008_tailwanese-bible/JSON格式資料')
