#!python
from os import makedirs
from os.path import isdir, join
from posix import listdir
from sys import argv
from 詞頻doc.轉換doc import 轉換doc


def 轉規个資料夾(來源, 目標):
    makedirs(目標, exist_ok=True)
    for 檔名 in listdir(來源):
        檔案 = 檔名
        if isdir(join(來源, 檔名)):
            轉規个資料夾(join(來源, 檔名), join(目標, 檔名))
        else:
            with open(檔案, 'w') as 寫檔:
                print(
                    轉換doc(檔案).doc轉html().html轉array().array轉json().提json(),
                    file=寫檔
                )

if __name__ == '__main__':
    if len(argv) != 3:
        print('{} doc的資料夾 json的資料夾'.format(argv[0]))
    if not isdir(argv[1]):
        print('參數愛是資料夾')
    轉規个資料夾(argv[1], argv[2])
